services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=organizadorprojetodb'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
    ports:
      - '3306:3306'

